### ISSUE TITLE
Android client crashes: StackCorrpution arround getifaddrs() and pthread_mutex_lock called on a destroyed mutex libGVR

### ISSUE THREAD

**Issue by atesin** [ShootingKing-AM/PhoneVR#43]
steps and descriptions:
- i install server on steam windows as instructed (registering driver also)
- launch phonevr android debug app
- launch steamvr on pc
- phonevr chashes on android
- steamvr seems to continue but without connection to android client (visor no encontrado = viewer not found)
- ...
- close everything and start android client again
- open steamvr again
- a message displays "un componente clave de steamvr no funciona correctamente, reinicia steamvr" (a key steamvr component doesnt work, restart steamvr)
- ...
- restart steamvr (from steam, i.e. leaving steam open)
- a popups displays = "se ha producido un error al actualizar steamvr, la aplicacion se esta ejecutando (an error has occured when updating steamvr, the application is running)
- ...
- close everything steam and start steamvr again
- same as above (a key component doesnt work blah...)
- steamvr settings doesnt work also (does nothing)

more info:
- android pie
- armv8 (tested with armv7 = same result)
- windows 7 x64 ultimate spanish
- same results with pvr v0.1 from beta 53 and below

logs:
```
00:37:16-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:37:16-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:37:16-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:37:16-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:37:16-10.11.2020 - PVR-JNI-I: JNI startAnnouncer: :33333
00:37:16-10.11.2020 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
00:37:16-10.11.2020 - PVR-JNI-I: JNI stopAnnouncer
00:37:20-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:37:20-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:37:20-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:37:20-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:37:20-10.11.2020 - PVR-JNI-I: JNI startAnnouncer: :33333
00:37:20-10.11.2020 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer] TCP error: Bad address
00:37:20-10.11.2020 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
00:37:22-10.11.2020 - PVR-JNI-I: JNI stopAnnouncer
00:39:17-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:39:17-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:39:17-10.11.2020 - PVR-JNI-I: JNI startAnnouncer: :33333
00:39:17-10.11.2020 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer] TCP error: Bad address
00:39:17-10.11.2020 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
00:50:26-10.11.2020 - PVR-JNI-I: JNI callJavaMethod: Calling segueToGame
00:50:26-10.11.2020 - PVR-JNI-I: JNI stopAnnouncer
00:50:26-10.11.2020 - PVR-JNI-I: JNI createRenderer
00:50:26-10.11.2020 - PVR-JNI-I: JNI startSendSensorData 51423
00:50:26-10.11.2020 - PVR-JNI-I: JNI onResume
00:59:34-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:59:34-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:59:34-10.11.2020 - PVR-JNI-I: --------------------------------------------------------------------------------
00:59:34-10.11.2020 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
00:59:34-10.11.2020 - PVR-JNI-I: JNI startAnnouncer: :33333
00:59:34-10.11.2020 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
00:59:39-10.11.2020 - PVR-JNI-I: JNI stopAnnouncer
```

**Comment by ShootingKing-AM** [comment]
Hi, `a key steamvr component doesnt work, restart steamvr ` or `an error has occured when updating steamvr, the application is running` means that SteamVr is not closed properly. You need to close all processes related to SteamVr from Task Manager-> vrserver.exe, vrcore.exe, vrrenderer.exe etc etc ....

Which mobile phone are you using ? And dosent it show a "crash dialog" when the android app is crashed in latest build ?

**Comment by atesin** [comment]
i confirm i had none of these processes running, and used the .bat to close steam services from a previous pvr build also

my phone is an umidigi a5 pro (sold as gear gm30 here in chile by pcfactory)

**Comment by ShootingKing-AM** [comment]
Dont use .bat(s) anymore they are no longer supported, Can you share a screenshot of details page of Taskmanager ? And what about the Android Crash screen ? Btw we can discuss faster on Discord :D if you dont mind

**Comment by atesin** [comment]
additional requested logs ......

[pvr-logs.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5540316/pvr-logs.zip)

notes:
- i have no  PVRServer\ subfolder in "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\"
- i have no virtualis.phonevr/ subdirectory in <internal storage>/Android/data/
- i have no PVR/ subdirectory in <external storage>Android/data/virtualis.phonevr/files/

**Comment by dzid26** [comment]
Samsung Note8. Android 9. 
App closes few seconds after connection is established and screen goes in "persistence mode".
Server side [log](https://github.com/ShootingKing-AM/PhoneVR/files/5540342/pvrlog.txt)
is empty. And phone side log doesn't say much.

**Comment by thezofx** [comment]
.

**Comment by ShootingKing-AM** [comment]
@atesin @dzid26 Can you try the latest build and check if it solves your issues ?

**Comment by dzid26** [comment]
Still the app is just crashing. Ataching log from the app. 
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5609650/pvrlog.txt)

No log was written on the desktop side.

**Comment by ShootingKing-AM** [comment]
Logs were fixed in #47 itself. What's your directory structure in SteamVR folder ? Do you yourself/steamvr-running-user have write access to phone vr logs directory (you can manually write something in file and save it - to test this)?

**Comment by dzid26** [comment]
@ShootingKing-AM  Ok, I updated server side.  Now logs are working.  The latest phone app is still crashing though.
Attaching [pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5623835/pvrlog.txt).

**Comment by atesin** [comment]
hi... tested and the android app crashes immediately when open ... logs attached

specs:
- pvr v02 b60 armv8 debug
- android 9 pie stock
- device umidigi a5pro

[pvrDebuglog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5631514/pvrDebuglog.txt)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5631515/pvrlog.txt)

**Comment by ShootingKing-AM** [comment]
Hi @atesin and @dzid26, Latest beta0.2-62(53) fixed this issue, can you re-check if its working and revert? If its still not working, please attach the logs.

Thanks.

**Comment by atesin** [comment]
hi...  the new apk v02 b64 armv8 still crashes immediately when open
i sent you bug reports to phonevr.crash()gmail,com as said in documentation

thanks for your effort  (i am hungry to taste vr with my new phone xD... for the 1st time)

**Comment by thezofx** [comment]
> hi... the new apk v02 b64 armv8 still crashes immediately when open
> i sent you bug reports to phonevr.crash()gmail,com as said in documentation
> 
> i hope this information will be useful to fix it (i am hungry to taste vr for the 1st time, with my new phone xD)
> 
> thanks for your effort xD

@atesin if possible please share bug report with me also at rohitpanchal.zofx@gmail.com. Thanks.

**Comment by atesin** [comment]
@thezofx  done!

**Comment by ShootingKing-AM** [comment]
Thanks for the logs @atesin. The logs you shared pointed to two errors,

1. `Abort message: 'stack corruption detected (-fstack-protector)'` arround PrintNetworkInterfaceInfos() + getifaddrs() functions.
**Stacktrace:**
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Gear_Mobile/GM30/GM30:9/PPR1.180610.011/1559618766:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 27443, tid: 27474, name: alisres.phonevr  >>> viritualisres.phonevr <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'stack corruption detected (-fstack-protector)'
    x0  0000000000000000  x1  0000000000006b52  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000030
    x8  0000000000000083  x9  0000007d0507ab40  x10 fffffff87ffffbdf  x11 0000000000000001
    x12 0000000000000028  x13 000000005fc7be49  x14 00265fe67305eca0  x15 000042f66d89e9c2
    x16 0000007d050b32c8  x17 0000007d04ff12d8  x18 0000007c67b3972a  x19 0000000000006b33
    x20 0000000000006b52  x21 0000000000000083  x22 00006b3300006b33  x23 0000000000000011
    x24 0000007c67b3a570  x25 0000007c67a3d000  x26 0000007d090f15e0  x27 0000007c67d40790
    x28 0000007ff22f81d0  x29 0000007c67b39b80
    sp  0000007c67b39b40  lr  0000007d04fe5a90  pc  0000007d04fe5abc

backtrace:
    #00 pc 0000000000021abc  /system/lib64/libc.so (abort+124)
    #01 pc 000000000006f43c  /system/lib64/libc.so (__stack_chk_fail+20)
    #02 pc 00000000000c0048  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #03 pc 00000000000beb94  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #04 pc 00000000000be5c4  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so (getifaddrs+464)
    #05 pc 00000000000f7ab4  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so (PrintNetworkInterfaceInfos+40)
    #06 pc 00000000000ffe4c  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #07 pc 00000000000ffb4c  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #08 pc 00000000000ffaec  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #09 pc 00000000000ff810  /data/app/viritualisres.phonevr-QJLfw_zaBvF1A44RiHU9vg==/lib/arm64/libnative-lib.so
    #10 pc 0000000000083114  /system/lib64/libc.so (__pthread_start(void*)+36)
    #11 pc 00000000000233bc  /system/lib64/libc.so (__start_thread+68)
```
2. `Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xedf7f2f8)'` arround gvr_swap_chain_destroy() in libgvr.so (Google VR library)
**Stacktrace:**
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Gear_Mobile/GM30/GM30:9/PPR1.180610.011/1559618766:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 26176, tid: 26425, name: GLThread 1120  >>> viritualisres.phonevr <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xedf7f2f8)'
    r0  00000000  r1  00006739  r2  00000006  r3  00000008
    r4  00006640  r5  00006739  r6  cc34f914  r7  0000010c
    r8  d1181024  r9  e814fc80  r10 d0ca0560  r11 00000001
    ip  cc34f8b0  sp  cc34f900  lr  ee5b2e59  pc  ee5aaca6

backtrace:
    #00 pc 0001cca6  /system/lib/libc.so (abort+58)
    #01 pc 00064573  /system/lib/libc.so (__fortify_fatal(char const*, ...)+26)
    #02 pc 00063d75  /system/lib/libc.so (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+20)
    #03 pc 00063ca3  /system/lib/libc.so (pthread_mutex_lock+214)
    #04 pc 000f10e9  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #05 pc 000daecd  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #06 pc 000db01d  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #07 pc 0003435b  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #08 pc 00070f0d  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #09 pc 000dbfaf  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #10 pc 000b6cd9  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #11 pc 000baa6b  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #12 pc 000baa85  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #13 pc 0007bb69  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #14 pc 0002e7e5  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #15 pc 0002e7fd  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #16 pc 0002e23d  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #17 pc 00031bbf  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #18 pc 00031cc5  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #19 pc 00031d63  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so
    #20 pc 000237b5  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libgvr.so (gvr_swap_chain_destroy+64)
    #21 pc 0005a7ff  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so (_ZN3gvr11WrapperBaseI15gvr_swap_chain_XadL_Z22gvr_swap_chain_destroyEEED2Ev+12)
    #22 pc 0005a7e5  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so
    #23 pc 00059a1d  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so
    #24 pc 000654b1  /system/lib/libc.so (__cxa_finalize+132)
    #25 pc 0001827b  /system/lib/libc.so (exit+10)
    #26 pc 0006084f  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so
    #27 pc 00060235  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so (Renderer::initProg(std::__ndk1::vector<std::__ndk1::pair<unsigned int, bool>, std::__ndk1::allocator<std::__ndk1::pair<unsigned int, bool>>>, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>)+256)
    #28 pc 00060481  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so (Renderer::Renderer(std::__ndk1::vector<std::__ndk1::pair<unsigned int, bool>, std::__ndk1::allocator<std::__ndk1::pair<unsigned int, bool>>>, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, float, float)+116)
    #29 pc 00059b29  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so (PVRInitSystem+224)
    #30 pc 00052473  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/lib/arm/libnative-lib.so (Java_viritualisres_phonevr_Wrap_initSystem+102)
    #31 pc 0006e4d1  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/oat/arm/base.odex (offset 0x6c000) (viritualisres.phonevr.Wrap.initSystem+120)
    #32 pc 0040d775  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #33 pc 003e6de1  /system/lib/libart.so (art_quick_invoke_stub+224)
    #34 pc 000a1015  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
    #35 pc 001e5af9  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
    #36 pc 001e1425  /system/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+608)
    #37 pc 003e40e3  /system/lib/libart.so (MterpInvokeVirtualQuickRange+306)
    #38 pc 00404394  /system/lib/libart.so (ExecuteMterpImpl+30100)
    #39 pc 0014b44e  /data/app/viritualisres.phonevr-PwSwHNTB4M-q-blx4L6kLQ==/oat/arm/base.vdex (viritualisres.phonevr.GameActivity$Renderer.onSurfaceCreated+222)
    #40 pc 001c4d63  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2667418923+378)
    #41 pc 001c938f  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
    #42 pc 003d5521  /system/lib/libart.so (artQuickToInterpreterBridge+880)
    #43 pc 00411cff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
    #44 pc 00910737  /system/framework/arm/boot-framework.oat (offset 0x3b5000) (android.opengl.GLSurfaceView$GLThread.guardedRun+2806)
    #45 pc 009117fd  /system/framework/arm/boot-framework.oat (offset 0x3b5000) (android.opengl.GLSurfaceView$GLThread.run+180)
    #46 pc 0040d775  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #47 pc 003e6de1  /system/lib/libart.so (art_quick_invoke_stub+224)
    #48 pc 000a1015  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
    #49 pc 00347ae5  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
    #50 pc 0034883d  /system/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+320)
    #51 pc 003697b7  /system/lib/libart.so (art::Thread::CreateCallback(void*)+866)
    #52 pc 00063305  /system/lib/libc.so (__pthread_start(void*)+22)
    #53 pc 0001de69  /system/lib/libc.so (__start_thread+24)
```
Will getback to you after finding out why this is happeneing. 👍

**Comment by ShootingKing-AM** [comment]
@atesin #57 attemps to fix the stack corrpution (Error 1 of 2) I didnt release another version yet, since my device dosent actually crash and i couldn't actually test it ^^

Anyways, you can get the [pre-built](https://ci.appveyor.com/project/ShootingKing-AM/phonevr/builds/37367538/job/g6ee17gi22cessbb/artifacts) beta-63 [here](https://ci.appveyor.com/api/buildjobs/g6ee17gi22cessbb/artifacts/PhoneVR-0.2-beta_63-master.zip). Just install the .apk from `PhoneVR.zip/android/arm7/release` and check if this fixes the issue.

@thezofx will soon be posting a fix for libGVR (Error 2 of 2)

Thanks !

**Comment by barkely128** [comment]
Sorry, but I have to say that even your latest build doesn't work for me. The app crashes a split second after Steamvr tries to establish a connection to it. Don't have time for full log file report rn, I'll try to provide some logs when I have time to tinker again, if testing new builds don't fix it. But my setup is Oneplus 5, with Lineageos 18.1 installed. (Android 11). Commercial VR apps work, so I don't think that's the issue.

**Comment by ShootingKing-AM** [comment]
Thanks for the logs @barkely128 

Your issue is different from this thread (not an unexpected crash). Opened a new issue on your behalf #60 Feel free to add any futher details there :)

**Comment by ShootingKing-AM** [comment]
@atesin Fixes are merged into main release. Try the latest release :)

**Comment by atesin** [comment]
it still crashes immediately, report txt sent from my phone by mail (could share here)

pvr 02b 65 apk armv8
android 9 pie
device umidigi a5pro (sold as gear gm30 by pcfactory.cl )

**Comment by ShootingKing-AM** [comment]
@atesin Thanks for the logs. I found the root cause of the issue, we were binding to port 0 to receive Netlink messages. Binding Port < 1024 is normally acceptable. But it seems some devices dont accept this. Removed this bind in latest release ! I guess now i can close this issue :D

**Comment by barkely128** [comment]
Great news. Thank you! I'll be sure to test it out.
I'm an idiot in Android, but I know a thing or two about Linux. 0-1024 ports are system ports in Linux. They normally can't be used by non-root users. Can be an issue for devices with tightened security. User port range (1024 to 49151) should be fine.
/etc/services usually contain a list with services using a particular port as the default.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by barkely128** [comment]
Still doesn't work. But I think there's some good progress. I got it to open the app and show me the VR mode. Although the screen showed a black picture only.

Btw, OS is Win10, Local firewall disabled.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ShootingKing-AM** [comment]
I see. Then this issue is solved pertaining to ifaddrs stackcorruption + NullException @ Insets.
Black screen issue seems same as in #55.

Will be closing this issue on @atesin confirms it.

**Comment by atesin** [comment]
mee??? ... sorry i was busy these days, but i will test last release now ... will answer soon

(my phone is the most tricky or is just my perception?)

**Comment by atesin** [comment]
tested phonevr version 0.2 beta 67:

- steamvr + pvr driver seem to launck ok, apk seem to start ok (finally!)... but they don't detect each other ... even with disabled windows defender and windows firewall (dont have more security for now), and configuring pc ip manually in apk, no success either

tested environment:

- windows 8.1 x64 + steam vr
- device umidigi a5pro (umidigi.com)
- android 9 pie
- apk armv8 non debug

sending logs phonevr.crash()gmail!com...

**Comment by ShootingKing-AM** [comment]
Related to #75 - will be fixed with #75
